### ISSUE TITLE
[BUG] Github action does not find my project

### ISSUE THREAD

**Issue by clockwork189** [FirebaseExtended/action-hosting-deploy#298]
I am running into a very weird bug that has had me stumped. The issue that I have is if I use my staging project Id: "metricwire.com:api-project-737636097603" the firebase build will fail. My guess is because it is not getting the project Id in th e build phase as indicated by this part in the error:
```
  /usr/local/bin/npx firebase-tools@latest hosting:channel:deploy pr8-github-actions --only app-staging --expires 7d --project *** --debug
```
I tried changing my projectId to anything else, literally anything else eg: "test", "staging", "abc" and while the build still fails (because I am using a non-existent project which I am aware of), the error log still shows:
```  
  /usr/local/bin/npx firebase-tools@latest hosting:channel:deploy pr8-github-actions --only app-staging --expires 7d --project test --debug
```

So my current problem is that if my projectId is "metricwire.com:api-project-737636097603" I get the *** in the build step and it fails otherwise it shows the proper project Id in the build debug.

My current workaround is to create a completely different firebase project for staging, but it is still curious that this issue occurs. 

### Error message

```
/usr/local/bin/npx firebase-tools@latest hosting:channel:deploy pr8-github-actions --only app-staging --expires 7d --project *** --json
  npm WARN exec The following package was not found and will be installed: firebase-tools@12.4.5
  npm WARN deprecated har-validator@5.1.5: this library is no longer supported
  npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/[31](https://github.com/MetricWire/research-m5/actions/runs/5613999017/job/15211305490#step:3:34)42
  npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  {
    "status": "error",
    "error": "Failed to authenticate, have you run \u001b[1mfirebase login\u001b[22m?"
  }
  {
    "status": "error",
    "error": "Failed to authenticate, have you run \u001b[1mfirebase login\u001b[22m?"
  }
  
  The process '/usr/local/bin/npx' failed with exit code 1
  Retrying deploy with the --debug flag for better error output
  /usr/local/bin/npx firebase-tools@latest hosting:channel:deploy pr8-github-actions --only app-staging --expires 7d --project *** --debug
  [2023-07-20T17:22:48.040Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
  [2023-07-20T17:22:48.060Z] SyntaxError: Unexpected token m in JSON at position 0
      at JSON.parse (<anonymous>)
      at ReadStream.<anonymous> (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/google-auth-library/build/src/auth/googleauth.js:375:43)
      at ReadStream.emit (node:events:513:28)
      at ReadStream.emit (node:domain:489:12)
      at endReadableNT (node:internal/streams/readable:1[35](https://github.com/MetricWire/research-m5/actions/runs/5613999017/job/15211305490#step:3:38)9:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
  
  Error: Failed to authenticate, have you run firebase login?
  [2023-07-20T17:22:48.040Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
  [2023-07-20T17:22:48.060Z] SyntaxError: Unexpected token m in JSON at position 0
      at JSON.parse (<anonymous>)
      at ReadStream.<anonymous> (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/google-auth-library/build/src/auth/googleauth.js:[37](https://github.com/MetricWire/research-m5/actions/runs/5613999017/job/15211305490#step:3:40)5:43)
      at ReadStream.emit (node:events:513:28)
      at ReadStream.emit (node:domain:489:12)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
  
  Error: Failed to authenticate, have you run firebase login?
  
  The process '/usr/local/bin/npx' failed with exit code 1
  Error: The process '/usr/local/bin/npx' failed with exit code 1
```

### Expected behavior
Successful Build

### Actual behavior

Build Fails

**Comment by marlier** [comment]
I'm running in to this same issue (or a very similar one).  My project is a next.js project that uses firebase's webframeworks experiment, and building/deploying as part of a Github Action is currently failing due to the project id not being found.

My project was set up using the `firebase init hosting:github` command, as documented at https://github.com/FirebaseExtended/action-hosting-deploy/blob/main/docs/service-account.md.  .github/firebase-hosting-pull-request.yml is:
```
# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: env
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CGN_SCHOOL_STAGING }}'
          projectId: cgn-school-staging
          expires: 7d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          NODE_ENV: staging
```

This configuration worked fine until I tried to enable Firebase Auth.  At that point the build began to fail.

The errors that I am getting look like this:
```
- info Generating static pages (0/17)
Error: Unable to detect a Project Id in the current environment. 
To learn more about authentication and Google APIs, visit: 
https://cloud.google.com/docs/authentication/getting-started
    at GoogleAuth.findAndCacheProjectId (/home/runner/work/roadmap/roadmap/node_modules/google-auth-library/build/src/auth/googleauth.js:124:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Firestore.initializeIfNeeded (/home/runner/work/roadmap/roadmap/node_modules/@google-cloud/firestore/build/src/index.js:1170:35)
Caused by: Error
    at Query._get (/home/runner/work/roadmap/roadmap/node_modules/@google-cloud/firestore/build/src/reference.js:1717:23)
    at Query.get (/home/runner/work/roadmap/roadmap/node_modules/@google-cloud/firestore/build/src/reference.js:1705:21)
    at /home/runner/work/roadmap/roadmap/.next/server/app/admin/cgn/schools/page.js:393:84
    at /home/runner/work/roadmap/roadmap/.next/server/chunks/780.js:8166:23
    at Page (/home/runner/work/roadmap/roadmap/.next/server/app/admin/cgn/schools/page.js:397:25)
    at preloadComponent (/home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/preload-component.js:23:22)
    at /home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:606:101
    at async createComponentTree (/home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:606:29)
    at async /home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:523:78
    at async Promise.all (index 0)

Error occurred prerendering page "/admin/cgn/schools". Read more: https://nextjs.org/docs/messages/prerender-error
- info Generating static pages (4/17)
Error: Unable to detect a Project Id in the current environment. 
To learn more about authentication and Google APIs, visit: 
https://cloud.google.com/docs/authentication/getting-started
    at GoogleAuth.findAndCacheProjectId (/home/runner/work/roadmap/roadmap/node_modules/google-auth-library/build/src/auth/googleauth.js:124:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Firestore.initializeIfNeeded (/home/runner/work/roadmap/roadmap/node_modules/@google-cloud/firestore/build/src/index.js:1170:35)
Caused by: Error
    at Query._get (/home/runner/work/roadmap/roadmap/node_modules/@google-cloud/firestore/build/src/reference.js:1717:23)
    at Query.get (/home/runner/work/roadmap/roadmap/node_modules/@google-cloud/firestore/build/src/reference.js:1705:21)
    at /home/runner/work/roadmap/roadmap/.next/server/app/admin/cgn/schools/page.js:393:84
    at /home/runner/work/roadmap/roadmap/.next/server/chunks/780.js:8166:23
    at Page (/home/runner/work/roadmap/roadmap/.next/server/app/admin/cgn/schools/page.js:397:25)
    at preloadComponent (/home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/preload-component.js:23:22)
    at /home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:606:101
    at async createComponentTree (/home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:606:29)
    at async /home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:523:78
    at async Promise.all (index 0)
- info Generating static pages (8/17)
Error: Unable to detect a Project Id in the current environment. 
To learn more about authentication and Google APIs, visit: 
https://cloud.google.com/docs/authentication/getting-started
    at GoogleAuth.findAndCacheProjectId (/home/runner/work/roadmap/roadmap/node_modules/google-auth-library/build/src/auth/googleauth.js:124:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Firestore.initializeIfNeeded (/home/runner/work/roadmap/roadmap/node_modules/@google-cloud/firestore/build/src/index.js:1170:35)
Caused by: Error
    at Query._get (/home/runner/work/roadmap/roadmap/node_modules/@google-cloud/firestore/build/src/reference.js:1717:23)
    at Query.get (/home/runner/work/roadmap/roadmap/node_modules/@google-cloud/firestore/build/src/reference.js:1705:21)
    at /home/runner/work/roadmap/roadmap/.next/server/app/admin/cgn/schools/page.js:393:84
    at /home/runner/work/roadmap/roadmap/.next/server/chunks/780.js:8166:23
    at Page (/home/runner/work/roadmap/roadmap/.next/server/app/admin/cgn/schools/page.js:397:25)
    at preloadComponent (/home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/preload-component.js:23:22)
    at /home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:606:101
    at async createComponentTree (/home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:606:29)
    at async /home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:523:78
    at async Promise.all (index 0)
Caused by: Error
    at CollectionReference._get (/home/runner/work/roadmap/roadmap/node_modules/@google-cloud/firestore/build/src/reference.js:1717:23)
    at CollectionReference.get (/home/runner/work/roadmap/roadmap/node_modules/@google-cloud/firestore/build/src/reference.js:1705:21)
    at /home/runner/work/roadmap/roadmap/.next/server/app/library/page.js:292:[55](https://github.com/collegeguidancenetwork/roadmap/pull/8/checks#step:4:56)
    at /home/runner/work/roadmap/roadmap/.next/server/chunks/780.js:8166:23
    at Page (/home/runner/work/roadmap/roadmap/.next/server/app/library/page.js:296:25)
    at preloadComponent (/home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/preload-component.js:23:22)
    at /home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:606:101
    at async createComponentTree (/home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:606:29)
    at async /home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:523:78
    at async Promise.all (index 0)

Error occurred prerendering page "/library". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Unable to detect a Project Id in the current environment. 
To learn more about authentication and Google APIs, visit: 
https://cloud.google.com/docs/authentication/getting-started
    at GoogleAuth.findAndCacheProjectId (/home/runner/work/roadmap/roadmap/node_modules/google-auth-library/build/src/auth/googleauth.js:124:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Firestore.initializeIfNeeded (/home/runner/work/roadmap/roadmap/node_modules/@google-cloud/firestore/build/src/index.js:1170:35)
Caused by: Error
    at Query._get (/home/runner/work/roadmap/roadmap/node_modules/@google-cloud/firestore/build/src/reference.js:1717:23)
    at Query.get (/home/runner/work/roadmap/roadmap/node_modules/@google-cloud/firestore/build/src/reference.js:1705:21)
    at /home/runner/work/roadmap/roadmap/.next/server/app/admin/cgn/schools/page.js:393:84
    at /home/runner/work/roadmap/roadmap/.next/server/chunks/780.js:8166:23
    at Page (/home/runner/work/roadmap/roadmap/.next/server/app/admin/cgn/schools/page.js:397:25)
    at preloadComponent (/home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/preload-component.js:23:22)
    at /home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:[60](https://github.com/collegeguidancenetwork/roadmap/pull/8/checks#step:4:61)6:101
    at async createComponentTree (/home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:606:29)
    at async /home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:523:78
    at async Promise.all (index 0)
Caused by: Error
    at CollectionReference._get (/home/runner/work/roadmap/roadmap/node_modules/@google-cloud/firestore/build/src/reference.js:1717:23)
    at CollectionReference.get (/home/runner/work/roadmap/roadmap/node_modules/@google-cloud/firestore/build/src/reference.js:1705:21)
    at /home/runner/work/roadmap/roadmap/.next/server/app/library/page.js:292:55
    at /home/runner/work/roadmap/roadmap/.next/server/chunks/780.js:8166:23
    at Page (/home/runner/work/roadmap/roadmap/.next/server/app/library/page.js:296:25)
    at preloadComponent (/home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/preload-component.js:23:22)
    at /home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:606:101
    at async createComponentTree (/home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:606:29)
    at async /home/runner/work/roadmap/roadmap/node_modules/next/dist/server/app-render/app-render.js:523:78
    at async Promise.all (index 0)
- info Generating static pages (12/17)
- info Generating static pages (17/17)
```

**Comment by Psycarlo** [comment]
Any fixes for this one?

**Comment by seth-acuitymd** [comment]
I wonder if this isn't actually something with the Firebase Action, but GitHub Actions itself thinking that your projectID is a secret value? If you pass it in as an environment variable to the workflow and call it that way, does anything change? 

Something like 

```
jobs:
    build_and_generate_previce:
        if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
        env:
          project-id: "metricwire.com:api-project-737636097603"
        runs-on: ubuntu-latest
        environment: Development-App
        steps:
            - uses: actions/checkout@v3
            # - run: npm ci && npm run build
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: "${{ secrets.GITHUB_TOKEN }}"
                  firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}"
                  projectId: ${{ env.project-id }}
                  target: "app-staging"
```

**Comment by Psycarlo** [comment]
> I wonder if this isn't actually something with the Firebase Action, but GitHub Actions itself thinking that your projectID is a secret value? If you pass it in as an environment variable to the workflow and call it that way, does anything change? 
> 
> 
> 
> Something like 
> 
> 
> 
> ```
> 
> jobs:
> 
>     build_and_generate_previce:
> 
>         if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
> 
>         env:
> 
>           project-id: "metricwire.com:api-project-737636097603"
> 
>         runs-on: ubuntu-latest
> 
>         environment: Development-App
> 
>         steps:
> 
>             - uses: actions/checkout@v3
> 
>             # - run: npm ci && npm run build
> 
>             - uses: FirebaseExtended/action-hosting-deploy@v0
> 
>               with:
> 
>                   repoToken: "${{ secrets.GITHUB_TOKEN }}"
> 
>                   firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}"
> 
>                   projectId: ${{ env.project-id }}
> 
>                   target: "app-staging"
> 
> ```

I don't think so because I have another project with the projectId like that and runs fine.

**Comment by chirag-biradar** [comment]
@clockwork189 did you find any fix?

**Comment by sinawatra** [comment]
Hello, can you try this, I have inspect and it might due to the confliction between the PR.yml and Merge.yml 
+firebase-hosting-merge.yml
name: Deploy to Firebase Hosting PR

on:
  pull_request:


+firebase-hosting-pull-request.yml
name: Deploy to Firebase Hosting Merge

on:
  push:
    branches:
      - main
